<a href="https://colab.research.google.com/github/Ayomx/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/AMPIT_Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE
## Assignment 3 : Matrices

### Objectives
At the end of this activity you will be able to:
1. Understand the concept of matrices and how they relate to linear equations.
2. Basic matrix operations are performed.
3. Python is a programming language that can be used to program and translate matrix equations and operations.


# Discussion

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline


## Matrices
Matrices are a column-by-row rectangular array of numbers. In statistics, matrix algebra is used to represent data sets. For a simple reason, we use different notation. It's easier to follow the laws of matrix math when you stick to conventions. If you have a list like this in elementary algebra: To accordance with convention, you'd adjust it and represent it in a complex equation type.

Let's say for example you have ***A*** and ***B*** as system of equation.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
      w-2x+3y-4z \\
      3w-x-2y+z \\
      2w-x+3y-2z
    \end{array}
\right.
$$

We could see that ***A*** is a system of 2 equations with 2 parameters. While ***B*** is a system of 3 equations with 3 parameters. We can represent them as matrices as:

$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
C=\begin{bmatrix} 1 & -2 & 3 & -4 \\ 3 & -1 & -2 & 1 \\ 2 & -1 & 3 & -2\end{bmatrix}
$$

So assuming that you already discussed the fundamental representation of matrices, their types, and operations. We'll proceed in doing them in here in Python.

## Declaring Matrices

The elements or entries of a matrix are the individual items (numbers, symbols, or phrases) that make up the matrix.

Two matrices can be added or removed element by element as long as they are the same size (have the same number of rows and columns). The rule for matrix multiplication, on the other hand, is that two matrices can only be multiplied if the first's number of columns equals the second's number of rows. A scalar from the related field can be multiplied element-by-element by any matrix.

Row vectors are matrices with a single row, and column vectors are matrices with a single column. A square matrix is a matrix with the same number of rows and columns. A matrix with no rows or columns, known as an empty matrix, is beneficial in particular situations, such as computer algebra applications.

Do note that the *size* of a matrix is *i x j.*

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


We already gone over some of the types of matrices as vectors but we'll further discuss them in this laboratory activity. Since you already know how to describe vectors using **shape**, **dimensions** and **size** attributes, we'll use them to analyze the matrices.

In [10]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')


In [11]:
## Declaring a 2 x 2 matrix
A = np.array([
    [1, 9],
    [5, 3]
])
describe_mat(A)


Matrix:
[[1 9]
 [5 3]]

Shape:	(2, 2)
Rank:	2



In [12]:
G = np.array([
    [4,2,6],
    [5,3,1]
])
describe_mat(G)

Matrix:
[[4 2 6]
 [5 3 1]]

Shape:	(2, 3)
Rank:	2



In [13]:
## Declaring a 3 x 2 matrix
B = np.array([
    [5, 5],
    [3, 3],
    [2, 2]
])
describe_mat(B)


Matrix:
[[5 5]
 [3 3]
 [2 2]]

Shape:	(3, 2)
Rank:	2



In [14]:
H = np.array([6,4,1,2])
describe_mat(H)


Matrix:
[6 4 1 2]

Shape:	(4,)
Rank:	1



## Categorizing Matrices

There are several ways of classifying matrices. Once could be according to their **shape** and another is according to their **element values**. We'll try to go to them.

### According to Shape

#### Row and Column Matrices

In [15]:
## Declaring a Row Matrix

rowmatrix1D = np.array([
    1, 3, 2, -4
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3, -4]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(rowmatrix1D)
describe_mat(row_mat_2D)


Matrix:
[ 1  3  2 -4]

Shape:	(4,)
Rank:	1

Matrix:
[[ 1  2  3 -4]]

Shape:	(1, 4)
Rank:	2



In [16]:
## Declaring a Column Matrix

col_mat = np.array([
    [4],
    [6],
    [8]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)


Matrix:
[[4]
 [6]
 [8]]

Shape:	(3, 1)
Rank:	2



#### Square Matrices

A square matrix is known as an equal matrix. To put it another way, a square matrix is one in which the number of rows and columns in the matrix are equal.

In [17]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')


In [18]:
square_mat = np.array([
    [4,2,5],
    [5,2,7],
    [9,3,7]
])

non_square_mat = np.array([
    [1,3,5],
    [2,1,9]
])
describe_mat(square_mat)
describe_mat(non_square_mat)


Matrix:
[[4 2 5]
 [5 2 7]
 [9 3 7]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[1 3 5]
 [2 1 9]]

Shape:	(2, 3)
Rank:	2
Is Square: False



### According to Element Values

#### Null Matrix

A null matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

In [19]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')


In [20]:
null_mat = np.array([])
describe_mat(null_mat)


Matrix is Null


#### Zero Matrix

A zero matrix is a matrix of any dimension with all of its element entries being zeros.

In [21]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')


Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


#### Ones Matrix

A matrix of ones is a matrix in which all of the elements are one.

In [22]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')


Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


#### Diagonal Matrix

A diagonal matrix is a square matrix with all elements 0 except those in the diagonal from top left to bottom right.

In [24]:
np.array([
    [1,0,0],
    [0,2,0],
    [0,0,3]
])


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [25]:
d = np.diag([1,5,7,9])
#d.shape[0] == d.shape[1]
d

array([[1, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 9]])

#### Identity Matrix

An identity matrix is a square matrix of any order that has one value on its principal diagonal elements and zero values on the remainder of the matrix components.

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

#### Upper Triangular Matrix

An upper triangular matrix is a square matrix in which all of the elements below the left-right diagonal are 0.

In [28]:
np.array([
    [1,2,3,4],
    [0,3,1,-1],
    [0,0,5,2],
    [0,0,0,2]
])


array([[ 1,  2,  3,  4],
       [ 0,  3,  1, -1],
       [ 0,  0,  5,  2],
       [ 0,  0,  0,  2]])

In [29]:
F = np.array([
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
])
np.triu(F)


array([[ 2, -3,  4, -5,  6],
       [ 0, -3,  4, -5,  6],
       [ 0,  0,  4, -5,  6],
       [ 0,  0,  0, -5,  6],
       [ 0,  0,  0,  0,  6]])

#### Lower Triangular Matrix

A lower triangular matrix is a square matrix with all elements 0 above the left-right diagonal.

In [30]:
np.tril(F)

array([[ 2,  0,  0,  0,  0],
       [ 2, -3,  0,  0,  0],
       [ 2, -3,  4,  0,  0],
       [ 2, -3,  4, -5,  0],
       [ 2, -3,  4, -5,  6]])

In [31]:
np.array([
    [1,0,0,0],
    [5,3,0,0],
    [1,-4,5,0],
    [2,-3,9,2]
])


array([[ 1,  0,  0,  0],
       [ 5,  3,  0,  0],
       [ 1, -4,  5,  0],
       [ 2, -3,  9,  2]])

#Matrix Algebra

##Addition

If you want to combine two matrices, they must have the same dimensions. In other words, a 2 x 2 matrix can be added to another 2 x 2 matrix, but a 2 x 3 matrix cannot. It's fairly similar to adding matrices. Adding the same numbers in the same place is all that is required.

In [32]:
A = np.array([
    [5,3],
    [9,1],
    [3,2]
])
B = np.array([
    [1,3],
    [0,4],
    [1,7]
])
A+B

array([[6, 6],
       [9, 5],
       [4, 9]])

In [33]:
2+A ##Broadcasting
# 2*np.ones(A.shape)+A

array([[ 7,  5],
       [11,  3],
       [ 5,  4]])

##Subtraction

In [34]:
A-B

array([[ 4,  0],
       [ 9, -3],
       [ 2, -5]])

In [35]:
3-B == 3*np.ones(B.shape)-B

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

##Element-wise Multiplication

In [36]:
A*B
np.multiply(A,B)

array([[ 5,  9],
       [ 0,  4],
       [ 3, 14]])

In [37]:
2*A

array([[10,  6],
       [18,  2],
       [ 6,  4]])

In [38]:
A@B

ValueError: ignored

#Activity

##Task 1

Create a function named mat_desc() that thoroughly describes a matrix, it should:

*   Displays the shape, size, and rank of the matrix.
*   Displays whether the matrix is square or non-square.
*   Displays whether the matrix is an empty matrix.
*   Displays if the matrix is an identity, ones, or zeros matrix.

Use 5 sample matrices in which their shapes are not lower than **(3, 3)**. In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [39]:
## Function area and matrix declarations
def mat_desc(mat):
    square = False
    iden = np.identity(mat.shape[0])
    one = np.ones((mat.shape[0], mat.shape[1]))
    zero = np.zeros((mat.shape[0], mat.shape[1]))
    print(np.array)
    print("Shape:", mat.shape)
    print("Size:", mat.size)
    print("Rank:", np.linalg.matrix_rank(mat))
    if(mat.shape[0] == mat.shape[1]):
        square = True
        print("This matrix is square")
    else:
        print("This matrix is non-square")
    if(mat.shape[0] == 0 and mat.shape[1] == 0):
        print("This matrix is empty")
    else:
        print("This matrix is not empty")
    if(square and (iden == mat).all()):
        print("This is an identity matrix")
    elif((one == mat).all()):
        print("This is ones matrix")
    elif((zero == mat).all()):
        print("This is zeros matrix")
    else:
        print("This is neither an identity, nor ones, nor zeros matrix")

In [40]:
## Test Areas
A = np.array([
    [8,2,1],
    [5,8,2],
    [3,4,1]
])
mat_desc(A)

<built-in function array>
Shape: (3, 3)
Size: 9
Rank: 3
This matrix is square
This matrix is not empty
This is neither an identity, nor ones, nor zeros matrix


In [41]:
B = np.array([
    [0,0,0],
    [0,0,0],
    [0,0,0]
])
mat_desc(B)

<built-in function array>
Shape: (3, 3)
Size: 9
Rank: 0
This matrix is square
This matrix is not empty
This is zeros matrix


In [42]:
C = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1]
])
mat_desc(C)

<built-in function array>
Shape: (3, 3)
Size: 9
Rank: 3
This matrix is square
This matrix is not empty
This is an identity matrix


In [43]:
D = np.array([
    [1,1,1],
    [1,1,1],
    [1,1,1]
])
mat_desc(D)

<built-in function array>
Shape: (3, 3)
Size: 9
Rank: 1
This matrix is square
This matrix is not empty
This is ones matrix


In [44]:
E = np.array([
    [1,1],
    [1,1],
    [1,1]
])
mat_desc(E)

<built-in function array>
Shape: (3, 2)
Size: 6
Rank: 1
This matrix is non-square
This matrix is not empty
This is ones matrix


In [50]:
X = int(input("Number of rows for 1st Matrix: "))
Y = int(input("Number of columns for 1st Matrix: ")) 
print("Entries per row (separated by space): ")  
entries_1 = list(map(int, input().split()))
 
num_entries_1 = len(entries_1)
area_dim_1 = X*Y

def describe_mat(matrix):
  is_square = True if matrix.shape[0] == matrix.shape[1] else False
  print(f'\nMatrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n\n')

##validation if the number of entry is not inclined in the product of row and column.
if (area_dim_1 != num_entries_1):
  print("Incorrect entry of data. You can only have as many entries as the sum of the number of rows and columns in your data.")
  raise ValueError("Error! Please make sure you enter the correct number of series in your submission.")

matrix_1 = np.array(entries_1).reshape(X, Y)

describe_mat (matrix_1)
##
A = int(input("Number of rows for 2nd Matrix: "))
B = int(input("Number of colums for 2nd Matrix: "))
print("Entries per row (separated by space): ")
entries_2 = list(map(int, input().split()))

num_entries_2 = len(entries_2)
area_dim_2 = A*B

##validation if the number of entry is not inclined in the product of row and column.
if (area_dim_2 != num_entries_2):
  print("Incorrect entry of data. You can only have as many entries as the sum of the number of rows and columns in your data.")
  raise ValueError("Error! Please make sure you enter the correct number of series in your submission.")

matrix_2 = np.array(entries_2).reshape(A, B)
describe_mat (matrix_2)
##
dec_operation = input ("Enter Your Desired Operation (+,-,*,/) : ")
##
if dec_operation == '+' or dec_operation.lower() == "addition": 
  Matrix_sum = matrix_1 + matrix_2
  print("The Sum of the two Matrices are: \n{}".format(Matrix_sum))
##SUBTRACTION##
if dec_operation == '-' or dec_operation.lower() == "subtraction": 
  Matrix_diff = matrix_1 - matrix_2
  print("The Difference of the two Matrices are: \n{}".format(Matrix_diff))
##MULTIPLICATION##
if dec_operation == '*' or dec_operation.lower() == "multiplication": 
  Matrix_prod = matrix_1 * matrix_2
  print("The Product of the two Matrices are: \n{}".format(Matrix_prod))
##DIVISION##
if dec_operation == '/' or dec_operation.lower() == "division": 
  Matrix_quo = matrix_1 / matrix_2
  print("The Quotient of the two Matrices are: \n{}".format(Matrix_quo))
##

Number of rows for 1st Matrix: 2
Number of columns for 1st Matrix: 2
Entries per row (separated by space): 
1 2 3 4

Matrix:
[[1 2]
 [3 4]]

Shape:	(2, 2)
Rank:	2
Is Square: True


Number of rows for 2nd Matrix: 2
Number of colums for 2nd Matrix: 2
Entries per row (separated by space): 
4 5 6 7

Matrix:
[[4 5]
 [6 7]]

Shape:	(2, 2)
Rank:	2
Is Square: True


Enter Your Desired Operation (+,-,*,/) : +
The Sum of the two Matrices are: 
[[ 5  7]
 [ 9 11]]


#References:

https://www.statisticshowto.com/matrices-and-matrix-algebra/

https://courses.lumenlearning.com/boundless-algebra/chapter/introduction-to-matrices/#:~:text=matrix%3A%20A%20rectangular%20arrangement%20of,representing%20graphs%20in%20graph%20theory.

https://www.math-only-math.com/square-matrix.html

https://www.studypug.com/algebra-help/zero-matrix

https://www.studypug.com/algebra-help/identity-matrix

https://www.definitions.net/definition/Matrix+of+ones
